/** Canonical plan slugs — must match plans.slug in the database. */
const PLAN_SLUGS = Object.freeze({
  TRIAL: "trial",
  BASIC: "basic",
  PRO: "pro",
  BUSINESS: "business",
});

const SUBSCRIPTION_ERROR_CODES = Object.freeze({
  SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",
  TRIAL_EXPIRED: "TRIAL_EXPIRED",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
  PRODUCT_LIMIT_REACHED: "PRODUCT_LIMIT_REACHED",
  AI_PLAN_REQUIRED: "AI_PLAN_REQUIRED",
  AI_TOKEN_LIMIT_EXCEEDED: "AI_TOKEN_LIMIT_EXCEEDED",
});

export { PLAN_SLUGS, SUBSCRIPTION_ERROR_CODES };
